require("src/client/huds/drawhud")
require("src/client/huds/tests/drawhudtest")
function DrawGame()
	setFont()
	GamestateGamePausingDrawGame()
	GamestateWorldCreationMenuDrawGame()
	GamestateMainMenuSettingsDrawGame()
	GamestatePlayingGameSettingsDrawGame()
	GamestateKeybindingMainSettingsDrawGame()
	GamestateKeybindingPlayingGameSettingsDrawGame()
	GamestateMainMenuDrawGame()
	GamestatePlayingGameDrawGame()
end
