--init global variables
Ffi = require("ffi")
ChunkSize = 16
SliceHeight = 8
WorldHeight = 128
TileWidth, TileHeight = 1 / 16, 1 / 16
TileDataSize = 3
TexturepathLuaCraft = "resources/assets/textures/"
BlockandtilesfolderLuaCraft = "blocksandtiles"
BlockTexturepathLuaCraft = BlockandtilesfolderLuaCraft .. "/blocks/"
LiquidTexturepathLuaCraft = BlockandtilesfolderLuaCraft .. "/liquid/"
TilesTexturepathLuaCraft = BlockandtilesfolderLuaCraft .. "/tiles/"
FinalAtlasSize = 256 -- TODO ADD Support for atlas 4096 size and more
Mathpi = math.pi
UserDirectory = Lovefilesystem.getUserDirectory()
Luacraftconfig = UserDirectory .. ".LuaCraft\\Luacraftconfig.txt"
GlobalVSync = Lovewindow.getVSync()
Font25 = Lovegraphics.newFont(25)
Font15 = Lovegraphics.newFont(15)
BlockTest = Lovegraphics.newImage(TexturepathLuaCraft .. "debug/defaulttexture.png")
DefaultTexture = BlockTest
GuiSprites = Lovegraphics.newImage(TexturepathLuaCraft .. "guis/gui.png")
MainMenuBackground = Lovegraphics.newImage("resources/assets/backgrounds/MainMenuBackground.png")
MainMenuSettingsBackground = Lovegraphics.newImage("resources/assets/backgrounds/Mainmenusettingsbackground.png")
PlayingGamePauseMenu = Lovegraphics.newImage("resources/assets/backgrounds/gameplayingpausemenu.png")
WorldCreationBackground = Lovegraphics.newImage("resources/assets/backgrounds/WorldCreationBackground.png")
ChunkBorders = Lovegraphics.newImage(TexturepathLuaCraft .. "debug/chunkborders.png")
LightValues = 16
GuiHotbarQuad = Lovegraphics.newQuad(0, 0, 182, 22, GuiSprites:getDimensions())
GuiHotbarSelectQuad = Lovegraphics.newQuad(0, 22, 24, 22 + 24, GuiSprites:getDimensions())
GuiCrosshair = Lovegraphics.newQuad(256 - 16, 0, 256, 16, GuiSprites:getDimensions())
LogicAccumulator = 0
PhysicsStep = true
CurrentCommand = ""
GamestateMainMenuSettings = "MainMenuSettings"
GamestateMainMenu = "MainMenu"
GamestatePlayingGame = "PlayingGame"
GamestatePlayingGameSettings = "playingGameSettings"
GamestateGamePausing = "GamePausing"
GamestateWorldCreationMenu = "WorldCreationMenu"
Gamestate = GamestateMainMenu
EnableF3 = false
EnableF8 = false
EnableTESTBLOCK = false
EnableCommandHUD = false
FixinputforDrawCommandInput = false
Renderdistancegetresetted = true
Modelalreadycreated = 0
ChunkBorderAlreadyCreated = 0
HudTimeLeft = 0
