local texturepath = "resources/assets/textures/"
local blockandtilesfolder = "blocksandtiles/"
local blocktexturepath = blockandtilesfolder .. "/blocks/"
local liquidtexturepath = blockandtilesfolder .. "/liquid/"
local tilestexturepath = blockandtilesfolder .. "/tiles/"
LuaCraftTextures = {
    grassTopTexture = texturepath .. blocktexturepath .. "grass/grass_top.png",
    grassBottomTexture = texturepath .. blocktexturepath .. "grass/grass_bottom.png",
    grassSideTexture = texturepath .. blocktexturepath .. "grass/grass_side.png",
    airTexture = texturepath .. blocktexturepath .. "air.png",
    bedrockTexture = texturepath .. blocktexturepath .. "bedrock.png",
    coalTexture = texturepath .. blocktexturepath .. "coal.png",
    cobbleTexture = texturepath .. blocktexturepath .. "cobble.png",
    dirtTexture = texturepath .. blocktexturepath .. "dirt.png",
    glassTexture = texturepath .. blocktexturepath .. "glass.png",
    glowstoneTexture = texturepath .. blocktexturepath .. "glowstone.png",
    goldTexture = texturepath .. blocktexturepath .. "gold.png",
    gravelTexture = texturepath .. blocktexturepath .. "gravel.png",
    ironTexture = texturepath .. blocktexturepath .. "iron.png",
    oak_leavesTexture = texturepath .. blocktexturepath .. "oak_leaves.png",
    oak_logsTopTexture = texturepath .. blocktexturepath .. "oak_logs/oak_top.png",
    oak_logsBottomTexture = texturepath .. blocktexturepath .. "oak_logs/oak_botton.png",
    oak_logsSideTexture = texturepath .. blocktexturepath .. "oak_logs/oak_side.png",
    oak_planksTexture = texturepath .. blocktexturepath .. "oak_planks.png",
    sandTexture = texturepath .. blocktexturepath .. "sand.png",
    spongeTexture = texturepath .. blocktexturepath .. "sponge.png",
    stoneTexture = texturepath .. blocktexturepath .. "stone.png",
    stone_brickTexture = texturepath .. blocktexturepath .. "stone_brick.png",
    lavaTexture = texturepath .. liquidtexturepath .. "/lava.png",
    lavastationaryTexture = texturepath .. liquidtexturepath .. "lava_stationary.png",
    waterTexture = texturepath .. liquidtexturepath .. "water.png",
    waterstationaryTexture = texturepath .. liquidtexturepath .. "water_stationary.png",
    oak_sapplingsTexture = texturepath .. tilestexturepath .. "oak_sapplings.png",
    roseflowerTexture = texturepath .. tilestexturepath .. "rose_flower.png",
    yellowflowerTexture = texturepath .. tilestexturepath .. "yellow_flower.png",
}