function love.conf(t)
	t.window.depth = 16
	t.identity = "LuaCraftSaves" -- Le nom du répertoire de sauvegarde (string)
	t.appendidentity = false -- Rechercher des fichiers dans le répertoire source avant le répertoire de sauvegarde (booléen)
	t.version = "11.5" -- La version de LÖVE pour laquelle ce jeu a été fait (string)
	t.console = false -- Ouvrir une console (boolean, Windows seulement)
	t.accelerometerjoystick = true -- Activer l'accéléromètre sur iOS et Android en l'exposant comme un joystick (boolean)
	t.externalstorage = false -- True pour enregistrer les fichiers (et lire depuis le répertoire de sauvegarde) dans un stockage externe sur Android (booléen)
	t.gammacorrect = true -- Activer le rendu de correction gamma, lorsqu'il est pris en charge par le système (booléen)

	t.audio.mixwithsystem = true -- Continue à jouer la musique de fond lors de l'ouverture de LOVE (booléen, iOS et Android seulement)

	t.window.title = "LuaCraft" -- Titre de la fenêtre (string)
	t.window.icon = nil -- Chemin du fichier vers une image à utiliser comme icône de la fenêtre (string)
	t.window.width = 1280 -- Largeur de la fenêtre (number)
	t.window.height = 720 -- Hauteur de la fenêtre (number)
	t.window.borderless = false -- Supprime toutes les bordures de la fenêtre (booléen)
	t.window.resizable = true -- Laissez la fenêtre être redimensionnable par l'utilisateur (booléen)
	t.window.minwidth = 1024 -- Largeur minimale de la fenêtre si elle est redimensionnée (number)
	t.window.minheight = 576 -- Hauteur minimale de la fenêtre si elle est redimensionnée (number)
	t.window.fullscreen = false -- Active le plein écran (booléen)
	t.window.fullscreentype = "desktop" -- Choisissez entre le mode plein écran "bureau" ou le mode plein écran "exclusif" (string)
	--t.window.vsync = 1 THIS IS MADE DYNAMICALLY WITH MENU SETTINGS IN THE GAME
	t.window.msaa = 0 -- Le nombre d'échantillons à utiliser avec l'anti-crénelage multi-échantillonné (number)
	t.window.display = 1 -- Index du moniteur où afficher la fenêtre (number)
	t.window.highdpi = false -- Activer le mode haute résolution pour la fenêtre sur un écran Retina (booléen)
	t.window.x = nil -- La position x de la fenêtre dans l'écran spécifié (number)
	t.window.y = nil -- La position y de la fenêtre dans l'écran spécifié (number)

	t.modules.audio = true -- Active le module audio (boolean)
	t.modules.data = true -- Active le module data (boolean)
	t.modules.event = true -- Active le module event (boolean)
	t.modules.font = true -- Active le module font (boolean)
	t.modules.graphics = true -- Active le module graphics (boolean)
	t.modules.image = true -- Active le module image (boolean)
	t.modules.joystick = true -- Active le module joystick (boolean)
	t.modules.keyboard = true -- Active le module keyboard (boolean)
	t.modules.math = true -- Active le module math (boolean)
	t.modules.mouse = true -- Active le module mouse (boolean)
	t.modules.physics = true -- Active le module physics (boolean)
	t.modules.sound = true -- Active le module sound (boolean)
	t.modules.system = true -- Active le module system (boolean)
	t.modules.thread = true -- Active le module thread (boolean)
	t.modules.timer = true -- Active le module timer (boolean), le désactiver résultera en un temps delta de 0 dans love.update
	t.modules.touch = true -- Active le module touch (boolean)
	t.modules.video = true -- Active le module video (boolean)
	t.modules.window = true -- Active le module window (boolean)
end
